/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_phantompowered_server4je_cipher_NativeCrypto */

#ifndef _Included_com_github_phantompowered_server4je_cipher_NativeCrypto
#define _Included_com_github_phantompowered_server4je_cipher_NativeCrypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_phantompowered_server4je_cipher_NativeCrypto
 * Method:    init
 * Signature: (Z[B)J
 */
JNIEXPORT jlong JNICALL Java_com_github_phantompowered_server4je_cipher_NativeCrypto_init
        (JNIEnv *, jobject, jboolean, jbyteArray);

/*
 * Class:     com_github_phantompowered_server4je_cipher_NativeCrypto
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_phantompowered_server4je_cipher_NativeCrypto_free
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_github_phantompowered_server4je_cipher_NativeCrypto
 * Method:    process
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_com_github_phantompowered_server4je_cipher_NativeCrypto_process
        (JNIEnv *, jobject, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
